### ISSUE TITLE
Not possible to share calendar with users or groups

### ISSUE THREAD

**Issue by jomettler** [owncloud/calendar#1244]
New calendars can only be shared via links. Old calendars still have the users they were orignially shared with, but its not possible to share them with any other user.
![grafik](https://user-images.githubusercontent.com/80679433/162728786-4290df29-9013-4d96-bc77-5754afd29e7b.png)

### Steps to reproduce
1. Calendar
2. click share button

### Expected behaviour
option to share calendar with user, group or via link

### Actual behaviour
only option is to share via public link

### Server configuration

**Operating system**: Ubuntu 20.04 LTS

**Web server:** Apache/2.4.41 (Ubuntu)

**Database:** MYSQL (8.0.28-0ubuntu0.20.04.3 (Ubuntu))

**PHP version:** PHP 7.3.33-1+ubuntu20.04.1+deb.sury.org+1 (cli)

**ownCloud version:** ownCloud 10.8.0 (production) 

**Calendar version:** 1.6.4

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - calendar:
    - Version: 1.6.4
    - Path: /var/www/owncloud/apps/calendar
  - dav:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.8.0
    - Path: /var/www/owncloud/apps/files_external
Disabled:
  - activity:
    - Path: /var/www/owncloud/apps/activity
  - comments:
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Path: /var/www/owncloud/apps/configreport
  - encryption:
    - Path: /var/www/owncloud/apps/encryption
  - external:
    - Path: /var/www/owncloud/apps/external
  - files_mediaviewer:
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_sharing:
    - Path: /var/www/owncloud/apps/files_sharing
  - files_trashbin:
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Path: /var/www/owncloud/apps/firstrunwizard
  - market:
    - Path: /var/www/owncloud/apps/market
  - notifications:
    - Path: /var/www/owncloud/apps/notifications
  - provisioning_api:
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Path: /var/www/owncloud/apps/systemtags
  - updatenotification:
    - Path: /var/www/owncloud/apps/updatenotification
  - user_external:
    - Path: /var/www/owncloud/apps/user_external
 ```   
**ownCloud configuration:**

´´´
{
    "system": {
        "instanceid": "ocwvkiy6jpnd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "wintermute.psychologie.uni-oldenburg.de",
            "wintermute.psychologie.uol.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "10.8.0.4",
        "dbname": "ocdb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "htaccess.RewriteBase": "\/owncloud",
        "updatechecker": false,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/marketplace.owncloud.com\/apps",
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox

**Operating system:**

**CalDAV-clients:**

### Logs
#### Web server error log
```

```

#### Log file (data/owncloud.log)
```
{"reqId":"YlG2ZHjFAZG@ctRUGVf1UgAAAAE","level":3,"time":"2022-04-09T18:37:56+02:00","remoteAddr":"removed","user":"removed","app":"no app in context","method":"GET","url":"\/owncloud\/settings\/personal","message":"Section id not found: \"sharing\". Apps should register settings sections in info.xml"}
```

#### Browser log
```
Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. [jquery.min.js:4:18306](removed/owncloud/core/vendor/jquery/dist/jquery.min.js?v=515a6838b1c18f4375a5c4c8b6c13137)

Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info. [moment-with-locales.js:291:21](removed/owncloud/core/vendor/moment/min/moment-with-locales.js?v=515a6838b1c18f4375a5c4c8b6c13137)

Attempting to call a FullCalendar method on an element with no calendar. 2 [vendor.min.js:1:349038](removed/owncloud/apps/calendar/js/public/vendor.min.js?v=515a6838b1c18f4375a5c4c8b6c13137)
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: removed/owncloud/core/vendor/jquery/dist/jquery.min.js?v=515a6838b1c18f4375a5c4c8b6c13137
Source-Map-Adresse: jquery.min.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: removed/owncloud/core/vendor/es6-promise/es6-promise.auto.js?v=515a6838b1c18f4375a5c4c8b6c13137
Source-Map-Adresse: es6-promise.auto.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: removed/owncloud/apps/calendar/js/public/vendor.min.js?v=515a6838b1c18f4375a5c4c8b6c13137
Source-Map-Adresse: vendor.min.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: removed/owncloud/apps/calendar/js/public/app.min.js?v=515a6838b1c18f4375a5c4c8b6c13137
Source-Map-Adresse: app.min.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: removed/owncloud/core/vendor/jquery/dist/jquery.min.js?v=515a6838b1c18f4375a5c4c8b6c13137
Source-Map-Adresse: jquery.min.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: removed/owncloud/apps/calendar/js/public/vendor.min.js?v=515a6838b1c18f4375a5c4c8b6c13137
Source-Map-Adresse: vendor.min.js.map
```
