### ISSUE TITLE
Cannot see "share" icon in Calendar on Safari

### ISSUE THREAD

**Issue by reckart** [owncloud/calendar#679]
At http://demo.owncloud.org/index.php/apps/calendar I cannot see the "share" button when I open the page in Safari 7.1.2. It is in the HTML code, but not visible.

Opening the same page in Firefox 35.0, the share button is visible.

Browser set to language "German" in both cases.

Moved from here: https://github.com/owncloud/core/issues/13588

**Comment by LukasReschke** [comment]
@Sugaroverdose Safari fun – interested? :)

**Comment by Sugaroverdose** [comment]
@LukasReschke i'm on it :)

**Comment by Sugaroverdose** [comment]
@LukasReschke, @reckart it's not Safari bug, but AdBlock, AdBlock Plus or uBlock. Adding domain to whitelist resolves issue in my case

**Comment by reckart** [comment]
Indeed, AdBlock is running. But shouldn't that affect all buttons? Why is only the share button affected?

**Comment by Sugaroverdose** [comment]
@reckart my guess - some rule looks for 'icon-share' class inside an 'a' element, something which blocks social buttons)

**Comment by Sugaroverdose** [comment]
Here's css rule it generates, when i tried to rewrite html:
```css
.icon-share, .share.stumble, #content > #center > .dose > .dosesingle, #content > #right > .dose > .dosesingle, #header + #content > #left > #rlblock_left {
    display: none !important;
}
```
so, adblock definitely doesn't like icon-share class
