### ISSUE TITLE
Clock times in chinese

### ISSUE THREAD

**Issue by Arcticold** [owncloud/calendar#788]
### Steps to reproduce
1. Set language under "Personal" to Estonian (Eesti).
2. Check calendar in day/week format.

### Expected behaviour
Clock times in proper 24hr format just like with British English for example.

### Actual behaviour
![screenshot from 2017-04-17 10-51-33](https://cloud.githubusercontent.com/assets/5424359/25083201/5ced59e2-235e-11e7-9e66-73ba88ded07b.png)

### Server configuration
**Operating system**: Linux Debian 8.7

**Web server:** Apache 2.4.10

**Database:**

**PHP version:** PHP 5.6.30

**Server version:** 9.1.4

**Calendar version:** 1.4.1

**Updated from an older installed version or fresh install: Updated from and older installed version

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - calendar: 1.4.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - user_ldap: 0.9.0
Disabled:
  - activity
  - comments
  - configreport
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - updatenotification
  - user_external

```

**The content of config/config.php:**

```
system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "datadirectory": "\/srv\/owncloud-data",
        "overwrite.cli.url": "https:\/\/example.com\/owncloud",
        "version": "9.1.4.2",
        "trusted_domains": [
            "example.com"
        ],
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "db",
        "dbtableprefix": "",
        "mail_domain": "maildomain.com",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "192.168.89.11",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 3,
        "overwritehost": "example.com",
        "overwriteprotocol": "https",
        "overwritecondaddr": "^192.168.89.20$",
        "maintenance": false,
        "theme": "",
        "updatechecker": false
    }
}
```
